const logisticCompanys =
  [{
    "code": "TXWL",
    "name": "天翔物流",
    "value": "天翔物流(TXWL)",
    "key": 48
  }, {
    "code": "KKE",
    "name": "京广速递",
    "value": "京广速递(KKE)",
    "key": 46
  }, {
    "code": "CRE",
    "name": "中铁快运",
    "value": "中铁快运(CRE)",
    "key": 45
  }, {
    "code": "YMDD",
    "name": "壹米滴答",
    "value": "壹米滴答(YMDD)",
    "key": 44
  }, {
    "code": "SHQ",
    "name": "华强物流",
    "value": "华强物流(SHQ)",
    "key": 43
  }, {
    "code": "FAST",
    "name": "快捷快递",
    "value": "快捷快递(FAST)",
    "key": 42
  }, {
    "code": "XB",
    "name": "新邦物流",
    "value": "新邦物流(XB)",
    "key": 41
  }, {
    "code": "UAPEX",
    "name": "全一快递",
    "value": "全一快递(UAPEX)",
    "key": 40
  }, {
    "code": "QFKD",
    "name": "全峰快递",
    "value": "全峰快递(QFKD)",
    "key": 39
  }, {
    "code": "GTO",
    "name": "国通快递",
    "value": "国通快递(GTO)",
    "key": 38
  }, {
    "code": "ESB",
    "name": "E速宝",
    "value": "E速宝(ESB)",
    "key": 37
  }, {
    "code": "UC",
    "name": "优速快递",
    "value": "优速快递(UC)",
    "key": 36
  }, {
    "code": "ZJS",
    "name": "宅急送",
    "value": "宅急送(ZJS)",
    "key": 35
  }, {
    "code": "DTW",
    "name": "大田",
    "value": "大田(DTW)",
    "key": 34
  }, {
    "code": "HOAU",
    "name": "天地华宇",
    "value": "天地华宇(HOAU)",
    "key": 33
  }, {
    "code": "JTJ",
    "name": "金泰捷",
    "value": "金泰捷(JTJ)",
    "key": 32
  }, {
    "code": "KERRY",
    "name": "嘉里大通",
    "value": "嘉里大通(KERRY)",
    "key": 31
  }, {
    "code": "KYE",
    "name": "跨越速运",
    "value": "跨越速运(KYE)",
    "key": 30
  }, {
    "code": "CP",
    "name": "城配",
    "value": "城配(CP)",
    "key": 29
  }, {
    "code": "YUNDAKY",
    "name": "韵达快运",
    "value": "韵达快运(YUNDAKY)",
    "key": 28
  }, {
    "code": "JDWL",
    "name": "京东物流",
    "value": "京东物流(JDWL)",
    "key": 27
  }, {
    "code": "ZTKY",
    "name": "中通快运",
    "value": "中通快运(ZTKY)",
    "key": 26
  }, {
    "code": "RQWL",
    "name": "荣庆物流",
    "value": "荣庆物流(RQWL)",
    "key": 25
  }, {
    "code": "JDKD",
    "name": "京东快递",
    "value": "京东快递(JDKD)",
    "key": 24
  }, {
    "code": "SURE",
    "name": "速尔",
    "value": "速尔(SURE)",
    "key": 23
  }, {
    "code": "SHSM",
    "name": "送货上门",
    "value": "送货上门(SHSM)",
    "key": 22
  }, {
    "code": "XXZTGW",
    "name": "线下自提-官网",
    "value": "线下自提-官网(XXZTGW)",
    "key": 21
  }, {
    "code": "NoExpress",
    "name": "线下自提",
    "value": "线下自提(NoExpress)",
    "key": 20
  }, {
    "code": "CJZF",
    "name": "厂家直发",
    "value": "厂家直发(CJZF)",
    "key": 19
  }, {
    "code": "LBEX",
    "name": "龙邦速递",
    "value": "龙邦速递(LBEX)",
    "key": 18
  }, {
    "code": "ANWL",
    "name": "安能物流",
    "value": "安能物流(ANWL)",
    "key": 17
  }, {
    "code": "CNEX",
    "name": "佳吉快运",
    "value": "佳吉快运(CNEX)",
    "key": 16
  }, {
    "code": "SF",
    "name": "顺丰速递",
    "value": "顺丰速递(SF)",
    "key": 15
  }, {
    "code": "TTKDEX",
    "name": "天天快递",
    "value": "天天快递(TTKDEX)",
    "key": 13
  }, {
    "code": "HTKY",
    "name": "百世快递",
    "value": "百世快递(HTKY)",
    "key": 12
  }, {
    "code": "ZTO",
    "name": "中通速递",
    "value": "中通速递(ZTO)",
    "key": 11
  }, {
    "code": "DBKD",
    "name": "德邦快递",
    "value": "德邦快递(DBKD)",
    "key": 10
  }, {
    "code": "DBL",
    "name": "德邦物流",
    "value": "德邦物流(DBL)",
    "key": 9
  }, {
    "code": "BEST",
    "name": "百世快运",
    "value": "百世快运(BEST)",
    "key": 8
  }, {
    "code": "YUNDA",
    "name": "韵达速递",
    "value": "韵达速递(YUNDA)",
    "key": 7
  }, {
    "code": "YTO",
    "name": "圆通速递",
    "value": "圆通速递(YTO)",
    "key": 6
  }, {
    "code": "STO",
    "name": "申通E物流",
    "value": "申通E物流(STO)",
    "key": 5
  }, {
    "code": "EYB",
    "name": "EMS经济快递",
    "value": "EMS经济快递(EYB)",
    "key": 4
  }, {
    "code": "EMS",
    "name": "EMS标快",
    "value": "EMS标快(EMS)",
    "key": 3
  }, {
    "code": "OTHER",
    "name": "其他",
    "value": "其他(OTHER)",
    "key": 2
  }]

module.exports = {
  logisticCompanys: logisticCompanys
}